### PR TITLE
fix: add adkit to .cspell.json

### PR DESCRIPTION
**Pull request by youtalk**
Fixed https://github.com/autowarefoundation/autoware/actions/runs/9091082555/job/24985001467?pr=4721

https://autoware.org/open-ad-kit/

### CODE REVIEW

**Comment by HansRobo** [comment]
I can't seem to find the use of "adkit" alone to mean "open-ad-kit" anywhere other than the place you pointed out.
Considering the frequency of the word "adkit", it is appropriate to treat it as a spelling variation that should be avoided rather than added to the dictionary.
The spell check also plays a role in suppressing unwarranted spelling variation, so I am cautious about adding it.

**Comment by youtalk** [comment]
This is not my opinion. It's originally from the current source code.

**Comment by HansRobo** [comment]
Yeah I got it.

@oguzkaganozt
From what I've searched, you seem to be the only user of "adkit" which means "Open AD Kit".
Is it okay to register "adkit" to the dictionary for spell check and accept it as a valid spelling variation of "Open AD Kit"?
(You are a key figure in Open AD Kit, so if you say yes I'll follow suit)

**Comment by oguzkaganozt** [comment]
I think the correct spelling should be the "openadkit" or "openadk" because both on the social media and in technical documentation there are always "open" keyword before "adkit". So I think rather than adding "adkit" as a valid spelling I am proposing to change below lines that are using "adkit" with "openadk":

https://github.com/autowarefoundation/autoware/blob/a79ef50498a6a301446f66e55e834fbc58e78362/.github/workflows/docker-build-and-push-main-self-hosted.yaml#L12

https://github.com/autowarefoundation/autoware/blob/a79ef50498a6a301446f66e55e834fbc58e78362/.github/workflows/docker-build-and-push-main.yaml#L12

**Comment by youtalk** [comment]
We no longer use `adkit`.
https://github.com/youtalk/autoware/pull/21

**Pull request closed without merging**
