### PR TITLE
feat(words): add pgrep

### PR DESCRIPTION
**Pull request by Yukio247**
pgrep reference is below.
https://ja.wikipedia.org/wiki/Pgrep

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@Yukio247 Please replace the reference link with a public one.

**Comment by Yukio247** [comment]
@kenji-miyake 
Sorry, I'm not quite sure about it, what should I use as the reference link?
I added a command helper script file to the specific pilot-auto product branch. And it is not the public. Do I have some solution on how to add the reference file of the public?

**Comment by kenji-miyake** [comment]
Please explain what is `pgrep`.
For example, Wikipedia is fine.
https://ja.wikipedia.org/wiki/Pgrep

**Comment by Yukio247** [comment]
@kenji-miyake 
Thank you very much for your kind support. I changed the detail of the PR.
Could you please re-review it? Thanks.

**Review by kenji-miyake — APPROVED** [review]

**Pull request merged**
