### PR TITLE
feat(words): add farocan

### PR DESCRIPTION
**Pull request by Yukio247**
FaroCAN: FARO Series CANBUS Module
https://www.antzer-tech.com/can-bus-mini-pcie-card

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@Yukio247 I think it should be renamed to like `faro-can`. Where is it used?

**Comment by Yukio247** [comment]
@kenji-miyake 
Thanks for reviewing! The `farocan` uses in [ecu-system-setup](https://github.com/tier4/autoware_ecu_system_setup/blob/main/roles/faro_can/tasks/main.yaml)
In this case, do I have to add both `faro-can` and `farocan`? Please let me know. Tanks!

**Comment by kenji-miyake** [comment]
@Yukio247 Mm, I see. Since it seems difficult to rename them all, I'll approve this PR.
By the way, don't you have to also add `farocand`?

**Review by kenji-miyake — APPROVED** [review]

**Comment by Yukio247** [comment]
@kenji-miyake 
Oops! I overlooked the things that spell check warned `farocand` also. Can I add the word `farocand` in this PR? Or should I create a new PR? Thank you for your cooperation.

**Comment by kenji-miyake** [comment]
You can add it here.

**Comment by Yukio247** [comment]
@kenji-miyake 
Thanks for that. I also added `farocand` word in this PR. https://github.com/tier4/autoware-spell-check-dict/pull/355/commits/c2f1edb18318ffeadb3655f72d86932f5fffb0de
Can I merge the PR?

**Comment by kenji-miyake** [comment]
Thanks. Yes, please!

**Pull request merged**
