### PR TITLE
Add tvmg and dltype

### PR DESCRIPTION
**Pull request by lexavtanke**
There are tvm_cli generated json files with `tvmg` and `dltype` words in tvm_utility package which are about to be merge  in https://github.com/autowarefoundation/autoware.universe/pull/4923. 
They produce [several warnings](https://github.com/autowarefoundation/autoware.universe/actions/runs/6576834337/job/17868093718?pr=4923) during the spell-check. And it is not possible to ignore them locally by `cspell: ignore` because comments aren't allowed in  json files.

### CODE REVIEW

**Comment by lexavtanke** [comment]
@HansRobo Hi, sorry for bothering you again but can you please review it?

Thank you in advance.

**Comment by HansRobo** [comment]
@lexavtanke 
Thank you for your contribution!
But, I'm being a little cautious about adding these words.
They don't seem to be a well-known or commonly seen abbreviation in the industry. 

Would you consider adding the words to local dict below?
https://github.com/autowarefoundation/autoware.universe/blob/main/.cspell-partial.json

This config file is not for surpessing warning in pull-request now, but we are planning to make cspell CI for all directories `required` on the pull-requests and the file will be base of its config file.
So, adding the words to the file means ignoring the words in cspell checks in the future.

**Comment by lexavtanke** [comment]
Hi @HansRobo! I've added tvmgen and dltype to local dict in [this PR](https://github.com/autowarefoundation/autoware.universe/pull/5420) but It produce [same errors](https://github.com/autowarefoundation/autoware.universe/actions/runs/6652898828/job/18081011536?pr=5420) by it self for now. 
When are you going to make the changes you mention above? 

Maybe we can merge this PR as temporal solution? and then changes in CI process will be done we can revert it back? 
Or maybe you can suggest some better solution?

**Comment by HansRobo** [comment]
@lexavtanke 
Sorry if my explanation is difficult to understand.
Could you add words to local dictionary not in [new PR](https://github.com/autowarefoundation/autoware.universe/pull/5420) but in existing in [your PR](https://github.com/autowarefoundation/autoware.universe/pull/4923)?
Then, the new dictionary words will be available in your PR and cspell errors will resolve!

**Comment by lexavtanke** [comment]
@HansRobo Thank you for your help!

**Pull request closed without merging**
