### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by kenji-miyake**

### CODE REVIEW

**Comment by kenji-miyake** [comment]
testing

**Comment by kenji-miyake** [comment]
mistake :pleading_face:

**Comment by kenji-miyake** [comment]
Result.
https://github.com/tier4/autoware-spell-check-dict/pull/46/checks?check_run_id=2880884289

**Comment by kenji-miyake** [comment]
Removed test commit.

**Review by kmiya — APPROVED** [review]
Thanks! LGTM.

**Pull request merged**
