### PR TITLE
feat(words): add 'localtime'

### PR DESCRIPTION
**Pull request by sasakisasaki**
As the title indicates :+1:

### CODE REVIEW

**Comment by HansRobo** [comment]
Please provide a link to prove the word exists, as other developers have done? 
This is important to clarify the origin of the word later.

**Comment by HansRobo** [comment]
"Logiee" is already in the dictionary, so why do we need to add an "logiee-ss"?
I expect the hyphen split the word and not cause an error.

**Comment by sasakisasaki** [comment]
@HansRobo Thank you so much for your review! Let me answer :+1: 

> Please provide a link to prove the word exists, as other developers have done? This is important to clarify the origin of the word later.

[Here](https://github.com/tier4/autoware_continuous_testing.logiee-ss/pull/2/files#diff-890e5a74b3902588cde745e63c3ab418aa51cbaa6ae4c81d1b0dae424b33a746R26) the `localtime` is used.

> "Logiee" is already in the dictionary, so why do we need to add an "logiee-ss"? I expect the hyphen split the word and not cause an error.

Oh, this is my misunderstanding! Yes, you are right, ```logiee-ss``` is not needed. Let me fix soon!

**Comment by sasakisasaki** [comment]
@HansRobo Fixed by [this commit](https://github.com/tier4/autoware-spell-check-dict/pull/786/commits/1b22aee22962016245b8e5c6fbf4e5e860d20ee5) :+1: . I do not see a `logiee-ss` related error in [this workflow](https://github.com/tier4/autoware_continuous_testing.logiee-ss/actions/runs/10788992245/job/29920966989?pr=2).

**Comment by HansRobo** [comment]
@HansRobo 
Thank you for the fix!

> [Here](https://github.com/tier4/autoware_continuous_testing.logiee-ss/pull/2/files#diff-890e5a74b3902588cde745e63c3ab418aa51cbaa6ae4c81d1b0dae424b33a746R26) the localtime is used.

Sorry, my explanation was confusing.
When I say "to prove the word exists," I don't mean to prove that the word exists in the place where you use it, but to prove that it exists in the public or industry and is worthy of being added to this repository, a "dictionary".

For example, "localtime" is a compound word consisting of "local" and "time" and should be used with clear word separation such as "local time"/"LocalTime"/"local_time" and should not be added to the dictionary.

If you still must add it, you must give a reason why, and the fact that you are using it or that it is causing you errors is not a reason.

All you need to do here is provide a reliable source of information like https://linux.die.net/man/3/localtime that explains the fact that in the context of Linux and C, the compound word "localtime" is commonly used without any separators.

This has become a long message, but it would be very helpful if you could pay attention to these things next time.
As for "localtime", I understand that it is commonly used in the industry, so there is no problem in adding it.

**Review by HansRobo — APPROVED** [review]

**Comment by HansRobo** [comment]
FYI, when you want to add a word, you can use useful workflows.
https://github.com/tier4/autoware-spell-check-dict#easy-to-add-a-word-using-workflow
(A PR created with this workflow will have a TODO asking you to provide a source link.)

**Comment by sasakisasaki** [comment]
@HansRobo Thanks, that really makes sense.

> If you still must add it, you must give a reason why, and the fact that you are using it or that it is causing you errors is not a reason.
> All you need to do here is provide a reliable source of information like https://linux.die.net/man/3/localtime that explains the fact that in the context of Linux and C, the compound word "localtime" is commonly used without any separators.

I got it and I have read the [guideline for contribution](https://github.com/tier4/autoware-spell-check-dict/blob/main/CONTRIBUTING.md) :+1: 

> FYI, when you want to add a word, you can use a useful workflow.
> https://github.com/tier4/autoware-spell-check-dict#easy-to-add-a-word-using-workflow

Oh! This is so useful! Thank you very much @HansRobo !

**Pull request merged**
