### PR TITLE
Add logsim

### PR DESCRIPTION
**Pull request by kenji-miyake**
It's intentionally duplicated and not sorted for CI test.

Please merge #2 first.

### CODE REVIEW

**Comment by kenji-miyake** [comment]
Rebased.

**Comment by kmiya** [comment]
There seems to be various names for our logging simulator, logsim and LSim.
I'm happy to merge this PR if "logsim" is one of the official abbreviation for the logging simulator.

**Comment by kenji-miyake** [comment]
It's our repository name!

**Comment by kmiya** [comment]
:+1: 
By the way, the GitHub action you contributed works perfectly! Awesome.

**Review by kmiya — APPROVED** [review]
Thank you!

**Pull request merged**
