### PR TITLE
Add git-related word `insteadof`

### PR DESCRIPTION
**Pull request by kenji-miyake**
https://gist.github.com/taoyuan/bfa3ff87e4b5611b5cbe

### CODE REVIEW

**Comment by kmiya** [comment]
According to the above link, we can write `.insteadOf` instead of `.insteadof`. Is that true?

**Comment by kenji-miyake** [comment]
hmm, probably. Should I fix them?

**Comment by kmiya** [comment]
> Should I fix them?

I don't think so. If we have a chance someday, let's fix our scripts.
Just in case, I would like to leave this PR as open.

**Comment by kenji-miyake** [comment]
Fixed. Will close this issue.

**Pull request closed without merging**
