### PR TITLE
feat(words): update word list

### PR DESCRIPTION
**Pull request by angry-crab**
Update word list for [docs: update instructions for multi-ternimal access](https://github.com/autowarefoundation/autoware/pull/103)

User defined environment variable:
- XSOCK
- XAUTH

Bash command and args related to X Server:
- xauth : https://www.ibm.com/docs/en/aix/7.2?topic=x-xauth-command
- nlist : https://www.ibm.com/docs/en/aix/7.2?topic=x-xauth-command
- nmerge : https://www.ibm.com/docs/en/aix/7.2?topic=x-xauth-command
- MITSHM : https://www.mit.edu/~arosinol/2019/08/06/Docker_Display_GUI_with_X_server/
- XAUTHORITY : https://docs.citrix.com/en-us/linux-virtual-delivery-agent/7-15-ltsr/configuration/configure-xauthority.html#:~:text=The%20.,connections%20to%20that%20specific%20display.

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@angry-crab Thank you!
Could you see seeing other PRs and write some references in the same way?
https://github.com/tier4/autoware-spell-check-dict/pulls?q=is%3Apr+is%3Aclosed

**Comment by kenji-miyake** [comment]
I have to update the CI script to support PRs from forks... Please wait for a while. :pray:

**Comment by angry-crab** [comment]
> @angry-crab Thank you! Could you see seeing other PRs and write some references in the same way? https://github.com/tier4/autoware-spell-check-dict/pulls?q=is%3Apr+is%3Aclosed

I've updated the description. Please let me know if it looks good.

**Comment by kenji-miyake** [comment]
Thank you, but `XSOCK`, `nlist`, and `MITSHM` aren't found in your link. :pleading_face:

**Comment by angry-crab** [comment]
> Thank you, but `XSOCK`, `nlist`, and `MITSHM` aren't found in your link. pleading_face

`XSOCK` is self-defined, `nlist` is described in the link if you scoll down. `MITSHM` (aka, `QT_X11_NO_MITSHM`) is an environment var used for graphics display.

**Comment by kenji-miyake** [comment]
Could you make it easy to review like this from next time? :pray: 
- nlist: https://www.ibm.com/docs/ja/zos/2.3.0?topic=functions-nlist-get-entries-from-name-list
- XSOCK: https://www.ibm.com/docs/ja/i/7.2?topic=browser-updating-configuration-files

**Comment by angry-crab** [comment]
> Could you make it easy to review like this from next time? pray
> 
> * nlist: https://www.ibm.com/docs/ja/zos/2.3.0?topic=functions-nlist-get-entries-from-name-list
> * XSOCK: https://www.ibm.com/docs/ja/i/7.2?topic=browser-updating-configuration-files

Sorry for the trouble. The description is updated.

**Comment by angry-crab** [comment]
@kenji-miyake Hi Miyake-san, it seems that `git` is failing during the sorting step. Do you know what's going on?

**Comment by kenji-miyake** [comment]
@angry-crab There is a problem with PRs from forks and I'm trying to fix it.
Since it will take a bit of time, you can leave this PR as it is or re-submit from the tier4 repository (not from your fork). I'll leave it to you.

**Comment by kenji-miyake** [comment]
Or if you are interested, you can try to work on this CI problem.

**Comment by angry-crab** [comment]
@kenji-miyake Thanks! I'll see what I can do with it.

**Comment by kenji-miyake** [comment]
Shima-san will introduce `pre-commit` to this repository and the problem will be fixed.

**Review by kenji-miyake — APPROVED** [review]

**Pull request merged**
